#ifndef _ALL_COMMAND_LIBRARIES_HPP_
#define _ALL_COMMAND_LIBRARIES_HPP_ 1

#include "CommandClass/GetAllSongsCommand.hpp"
#include "CommandClass/LoginCommand.hpp"
#include "CommandClass/LogoutCommand.hpp"
#include "CommandClass/ReadRequest.hpp"
#include "CommandClass/WriteRequest.hpp"
#include "CommandClass/DeleteRequest.hpp"
#include "CommandClass/GetSongCommand.hpp"
#include "CommandClass/SignupCommand.hpp"
#include "CommandClass/CommandManager.hpp"
#include "CommandClass/CommandParser.hpp"
#include "CommandClass/UtunesCommand.hpp"
#include "CommandClass/CommandEnums.hpp"
#include "CommandClass/GetLikesCommand.hpp"
#include "CommandClass/DeleteLikeCommand.hpp"
#include "CommandClass/AddLikeCommand.hpp"
#include "CommandClass/NewPlaylistCommand.hpp"
#include "CommandClass/GetAllPlaylistsCommand.hpp"
#include "CommandClass/AddSongToPlaylistCommand.hpp"
#include "CommandClass/GetPlaylistCommand.hpp"
#include "CommandClass/DeleteSongFrPlaylistCommand.hpp"
#include "CommandClass/GetCommentsCommand.hpp"
#include "CommandClass/AddCommentCommand.hpp"
#include "CommandClass/LikesFilterCommand.hpp"
#include "CommandClass/ReleaseYearFilterCommand.hpp"
#include "CommandClass/ArtistFilterCommand.hpp"
#include "CommandClass/NewFilterCommand.hpp"
#include "CommandClass/GetUsersCommand.hpp"
#include "CommandClass/GetRecommendedSongsCommand.hpp"
#include "CommandClass/GetSimilarUsersCommand.hpp"


#endif